// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnw1VRmSXNg7ZAsP6sEjr1JgC45XhbGQ0',
    appId: '1:462396187920:web:6c3924d11861482a3ff195',
    messagingSenderId: '462396187920',
    projectId: 'chat-app-d6bb3',
    authDomain: 'chat-app-d6bb3.firebaseapp.com',
    storageBucket: 'chat-app-d6bb3.firebasestorage.app',
    measurementId: 'G-B0X13BLTLX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0S-0b7Y1kHC1sIO5C9ms8rRbvTSKLNso',
    appId: '1:462396187920:android:01f4eef64a3d57fd3ff195',
    messagingSenderId: '462396187920',
    projectId: 'chat-app-d6bb3',
    storageBucket: 'chat-app-d6bb3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArCJLmlwctcvvyuD1Vva9Jtezci45MPNY',
    appId: '1:462396187920:ios:b2a72868e0e722263ff195',
    messagingSenderId: '462396187920',
    projectId: 'chat-app-d6bb3',
    storageBucket: 'chat-app-d6bb3.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAnw1VRmSXNg7ZAsP6sEjr1JgC45XhbGQ0',
    appId: '1:462396187920:web:b9987c3b35820af03ff195',
    messagingSenderId: '462396187920',
    projectId: 'chat-app-d6bb3',
    authDomain: 'chat-app-d6bb3.firebaseapp.com',
    storageBucket: 'chat-app-d6bb3.firebasestorage.app',
    measurementId: 'G-Y27M7RH2JE',
  );

}